source("receitas.R");
source("custos.R");
source("../Roptim1/blind.R");
source("../Roptim1/montecarlo.R");
# @param dia_um_procura_bud,
# @param dia_um_procura_stella,
# @param dia_dois_procura_bud,
# @param dia_dois_procura_stella,
# @param dia_tres_procura_bud,
# @param dia_tres_procura_stella,
# @param dia_quatro_procura_bud,
# @param dia_quatro_procura_stella,
# @param dia_cinco_procura_bud,
# @param dia_cinco_procura_stella,
# @param dia_seis_procura_bud,
# @param dia_seis_procura_stella,
# @param dia_sete_procura_bud,
# @param dia_sete_procura_stella,
# @param numero_iteracoes, Numero de iteracoes que nos queremos no algoritmo
# @param lower, (Os valores minimos que cada parametro pode tomar ex: c(0,0,0,...))
# @param upper, (Os valores maxidos que cada parametro pode tomar ex: c(10,10,10,10,...))
# @returns Os valores mais eficientes para a funcao
main <- function(
dia_um_procura_bud,
dia_um_procura_stella,
dia_dois_procura_bud,
dia_dois_procura_stella,
dia_tres_procura_bud,
dia_tres_procura_stella,
dia_quatro_procura_bud,
dia_quatro_procura_stella,
dia_cinco_procura_bud,
dia_cinco_procura_stella,
dia_seis_procura_bud,
dia_seis_procura_stella,
dia_sete_procura_bud,
dia_sete_procura_stella,
numero_iteracoes,
lower,
upper
){
#FUNCAO DE AVALIACAO
#  vetor, este é o vetor de onde irao resultar todos os parametros
# DIA 1
#  @param dia_um_sobras_bud,
# vetor[1],
#  @param dia_um_sobras_stella,
# vetor[2],
#  @param dia_um_v1,
# vetor[3],
#  @param dia_um_v2,
# vetor[4],
#  @param dia_um_v3,
# vetor[5],
#  @param dia_um_quantidade_bud_v1,
# vetor[6],
#  @param dia_um_quantidade_bud_v2,
# vetor[7],
#  @param dia_um_quantidade_bud_v3,
# vetor[8],
#  @param dia_um_quantidade_stella_v1,
# vetor[9],
#  @param dia_um_quantidade_stella_v2,
# vetor[10],
#  @param dia_um_quantidade_stella_v3,
# vetor[11],
#  @param dia_um_sera_fds,
# vetor[12],
#  @param dia_um_sera_normal,
# vetor[13],
#  @param dia_um_procura_bud,
# dia_um_procura_bud,
#  @param dia_um_procura_stella,
# dia_um_procura_stella,
#  @param dia_um_procura_real_bud,
# vetor[14],
#  @param dia_um_procura_real_stella
# vetor[15],
# DIA 2
#  @param dia_dois_sobras_bud,
# vetor[16],
#  @param dia_dois_sobras_stella,
# vetor[17],
#  @param dia_dois_v1,
# vetor[18],
#  @param dia_dois_v2,
# vetor[19],
#  @param dia_dois_v3,
# vetor[20],
#  @param dia_dois_quantidade_bud_v1,
# vetor[21],
#  @param dia_dois_quantidade_bud_v2,
# vetor[22],
#  @param dia_dois_quantidade_bud_v3,
# vetor[23],
#  @param dia_dois_quantidade_stella_v1,
# vetor[24],
#  @param dia_dois_quantidade_stella_v2,
# vetor[25],
#  @param dia_dois_quantidade_stella_v3
# vetor[26],
#  @param dia_dois_sera_fds,
# vetor[27],
#  @param dia_dois_sera_normal,
# vetor[28],
#  @param dia_dois_procura_bud,
# dia_dois_procura_bud,
#  @param dia_dois_procura_stella,
# dia_dois_procura_stella,
#  @param dia_dois_procura_real_bud,
# vetor[29],
#  @param dia_dois_procura_real_stella
# vetor[30],
# DIA 3
#  @param dia_tres_sobras_bud,
# vetor[31],
#  @param dia_tres_sobras_stella,
# vetor[32],
#  @param dia_tres_v1,
# vetor[33],
#  @param dia_tres_v2,
# vetor[34],
#  @param dia_tres_v3,
# vetor[35],
#  @param dia_tres_quantidade_bud_v1,
# vetor[36],
#  @param dia_tres_quantidade_bud_v2,
# vetor[37],
#  @param dia_tres_quantidade_bud_v3,
# vetor[38],
#  @param dia_tres_quantidade_stella_v1,
# vetor[39],
#  @param dia_tres_quantidade_stella_v2,
# vetor[40],
#  @param dia_tres_quantidade_stella_v3,
# vetor[41],
#  @param dia_tres_sera_fds,
# vetor[42],
#  @param dia_tres_sera_normal,
# vetor[43],
#  @param dia_tres_procura_bud,
# dia_tres_procura_bud,
#  @param dia_tres_procura_stella,
# dia_tres_procura_stella,
#  @param dia_tres_procura_real_bud,
# vetor[44],
#  @param dia_tres_procura_real_stella
# vetor[45],
# DIA 4
#  @param dia_quatro_sobras_bud,
# vetor[46],
#  @param dia_quatro_sobras_stella,
# vetor[47],
#  @param dia_quatro_v1,
# vetor[48],
#  @param dia_quatro_v2,
# vetor[49],
#  @param dia_quatro_v3,
# vetor[50],
#  @param dia_quatro_quantidade_bud_v1,
# vetor[51],
#  @param dia_quatro_quantidade_bud_v2,
# vetor[52],
#  @param dia_quatro_quantidade_bud_v3,
# vetor[53],
#  @param dia_quatro_quantidade_stella_v1,
# vetor[54],
#  @param dia_quatro_quantidade_stella_v2,
# vetor[55],
#  @param dia_quatro_quantidade_stella_v3,
# vetor[56],
#  @param dia_quatro_sera_fds,
# vetor[57],
#  @param dia_quatro_sera_normal,
# vetor[58],
#  @param dia_quatro_procura_bud,
# dia_quatro_procura_bud,
#  @param dia_quatro_procura_stella,
# dia_quatro_procura_stella,
#  @param dia_quatro_procura_real_bud,
# vetor[59],
#  @param dia_quatro_procura_real_stella
# vetor[60],
# @param dia 5
#  @param dia_cinco_sobras_bud,
# vetor[61],
#  @param dia_cinco_sobras_stella,
# vetor[62],
#  @param dia_cinco_v1,
# vetor[63],
#  @param dia_cinco_v2,
# vetor[64],
#  @param dia_cinco_v3,
# vetor[65],
#  @param dia_cinco_quantidade_bud_v1,
# vetor[66],
#  @param dia_cinco_quantidade_bud_v2,
# vetor[67],
#  @param dia_cinco_quantidade_bud_v3,
# vetor[68],
#  @param dia_cinco_quantidade_stella_v1,
# vetor[69],
#  @param dia_cinco_quantidade_stella_v2,
# vetor[70],
#  @param dia_cinco_quantidade_stella_v3,
# vetor[71],
#  @param dia_cinco_sera_fds,
# vetor[72],
#  @param dia_cinco_sera_normal,
# vetor[73],
#  @param dia_cinco_procura_bud,
# dia_cinco_procura_bud,
#  @param dia_cinco_procura_stella,
# dia_cinco_procura_stella,
#  @param dia_cinco_procura_real_bud,
# vetor[74],
#  @param dia_cinco_procura_real_stella
# vetor[75],
# @param dia 6
#  @param dia_seis_sobras_bud,
# vetor[76],
#  @param dia_seis_sobras_stella,
# vetor[77],
#  @param dia_seis_v1,
# vetor[78],
#  @param dia_seis_v2,
# vetor[79],
#  @param dia_seis_v3,
# vetor[80],
#  @param dia_seis_quantidade_bud_v1,
# vetor[81],
#  @param dia_seis_quantidade_bud_v2,
# vetor[82],
#  @param dia_seis_quantidade_bud_v3,
# vetor[83],
#  @param dia_seis_quantidade_stella_v1,
# vetor[84],
#  @param dia_seis_quantidade_stella_v2,
# vetor[85],
#  @param dia_seis_quantidade_stella_v3,
# vetor[86],
#  @param dia_seis_sera_fds,
# vetor[87],
#  @param dia_seis_sera_normal,
# vetor[88],
#  @param dia_seis_procura_bud,
# dia_seis_procura_bud,
#  @param dia_seis_procura_stella,
# dia_seis_procura_stella,
#  @param dia_seis_procura_real_bud,
# vetor[89],
#  @param dia_seis_procura_real_stella
# vetor[90],
# @param dia 7
#  @param dia_sete_sobras_bud,
# vetor[91],
#  @param dia_sete_sobras_stella,
# vetor[92],
#  @param dia_sete_v1,
# vetor[93],
#  @param dia_sete_v2,
# vetor[94],
#  @param dia_sete_v3,
# vetor[95],
#  @param dia_sete_quantidade_bud_v1,
# vetor[96],
#  @param dia_sete_quantidade_bud_v2,
# vetor[97],
#  @param dia_sete_quantidade_bud_v3,
# vetor[98],
#  @param dia_sete_quantidade_stella_v1,
# vetor[99],
#  @param dia_sete_quantidade_stella_v2,
# vetor[100],
#  @param dia_sete_quantidade_stella_v3,
# vetor[101],
#  @param dia_sete_sera_fds,
# vetor[102],
#  @param dia_sete_sera_normal,
# vetor[103],
#  @param dia_sete_procura_bud,
# dia_sete_procura_bud,
#  @param dia_sete_procura_stella,
# dia_sete_procura_stella,
#  @param dia_sete_procura_real_bud,
# vetor[104],
#  @param dia_sete_procura_real_stella
# vetor[105]
eval <- function(vetor){
lucro <- venda_global_calculator(
# dia_um_quantidade_bud_v1,
vetor[6],
# dia_um_quantidade_bud_v2,
vetor[7],
# dia_um_quantidade_bud_v3,
vetor[8],
# dia_um_quantidade_stella_v1,
vetor[9],
# dia_um_quantidade_stella_v2,
vetor[10],
# dia_um_quantidade_stella_v3,
vetor[11],
# dia_dois_quantidade_bud_v1,
vetor[21],
# dia_dois_quantidade_bud_v2,
vetor[22],
# dia_dois_quantidade_bud_v3,
vetor[23],
# dia_dois_quantidade_stella_v1,
vetor[24],
# dia_dois_quantidade_stella_v2,
vetor[25],
# dia_dois_quantidade_stella_v3,
vetor[26],
# dia_tres_quantidade_bud_v1,
vetor[36],
# dia_tres_quantidade_bud_v2,
vetor[37],
# dia_tres_quantidade_bud_v3,
vetor[38],
# dia_tres_quantidade_stella_v1,
vetor[39],
# dia_tres_quantidade_stella_v2,
vetor[40],
# dia_tres_quantidade_stella_v3,
vetor[41],
# dia_quatro_quantidade_bud_v1,
vetor[51],
# dia_quatro_quantidade_bud_v2,
vetor[52],
# dia_quatro_quantidade_bud_v3,
vetor[53],
# dia_quatro_quantidade_stella_v1,
vetor[54],
# dia_quatro_quantidade_stella_v2,
vetor[55],
# dia_quatro_quantidade_stella_v3,
vetor[56],
# dia_cinco_quantidade_bud_v1,
vetor[66],
# dia_cinco_quantidade_bud_v2,
vetor[67],
# dia_cinco_quantidade_bud_v3,
vetor[68],
# dia_cinco_quantidade_stella_v1,
vetor[69],
# dia_cinco_quantidade_stella_v2,
vetor[70],
# dia_cinco_quantidade_stella_v3,ç
vetor[71],
# dia_seis_quantidade_bud_v1,
vetor[81],
# dia_seis_quantidade_bud_v2,
vetor[82],
# dia_seis_quantidade_bud_v3,
vetor[83],
# dia_seis_quantidade_stella_v1,
vetor[84],
# dia_seis_quantidade_stella_v2,
vetor[85],
# dia_seis_quantidade_stella_v3,
vetor[86],
# dia_sete_quantidade_bud_v1,
vetor[96],
# dia_sete_quantidade_bud_v2,
vetor[97],
# dia_sete_quantidade_bud_v3,
vetor[98],
# dia_sete_quantidade_stella_v1,
vetor[99],
# dia_sete_quantidade_stella_v2,
vetor[100],
# dia_sete_quantidade_stella_v3
vetor[101]
) 
-
custo_total_calculator(
# DIA 1
#  dia_um_sobras_bud,
vetor[1],
#  dia_um_sobras_stella,
vetor[2],
#  dia_um_v1,
vetor[3],
#  dia_um_v2,
vetor[4],
#  dia_um_v3,
vetor[5],
#  dia_um_quantidade_bud_v1,
vetor[6],
#  dia_um_quantidade_bud_v2,
vetor[7],
#  dia_um_quantidade_bud_v3,
vetor[8],
#  dia_um_quantidade_stella_v1,
vetor[9],
#  dia_um_quantidade_stella_v2,
vetor[10],
#  dia_um_quantidade_stella_v3,
vetor[11],
#  dia_um_sera_fds,
vetor[12],
#  dia_um_sera_normal,
vetor[13],
#  dia_um_procura_bud,
dia_um_procura_bud,
#  dia_um_procura_stella,
dia_um_procura_stella,
#  dia_um_procura_real_bud,
vetor[14],
#  dia_um_procura_real_stella
vetor[15],
# DIA 2
#  dia_dois_sobras_bud,
vetor[16],
#  dia_dois_sobras_stella,
vetor[17],
#  dia_dois_v1,
vetor[18],
#  dia_dois_v2,
vetor[19],
#  dia_dois_v3,
vetor[20],
#  dia_dois_quantidade_bud_v1,
vetor[21],
#  dia_dois_quantidade_bud_v2,
vetor[22],
#  dia_dois_quantidade_bud_v3,
vetor[23],
#  dia_dois_quantidade_stella_v1,
vetor[24],
#  dia_dois_quantidade_stella_v2,
vetor[25],
#  dia_dois_quantidade_stella_v3
vetor[26],
#  dia_dois_sera_fds,
vetor[27],
#  dia_dois_sera_normal,
vetor[28],
#  dia_dois_procura_bud,
dia_dois_procura_bud,
#  dia_dois_procura_stella,
dia_dois_procura_stella,
#  dia_dois_procura_real_bud,
vetor[29],
#  dia_dois_procura_real_stella
vetor[30],
# DIA 3
#  dia_tres_sobras_bud,
vetor[31],
#  dia_tres_sobras_stella,
vetor[32],
#  dia_tres_v1,
vetor[33],
#  dia_tres_v2,
vetor[34],
#  dia_tres_v3,
vetor[35],
#  dia_tres_quantidade_bud_v1,
vetor[36],
#  dia_tres_quantidade_bud_v2,
vetor[37],
#  dia_tres_quantidade_bud_v3,
vetor[38],
#  dia_tres_quantidade_stella_v1,
vetor[39],
#  dia_tres_quantidade_stella_v2,
vetor[40],
#  dia_tres_quantidade_stella_v3,
vetor[41],
#  dia_tres_sera_fds,
vetor[42],
#  dia_tres_sera_normal,
vetor[43],
#  dia_tres_procura_bud,
dia_tres_procura_bud,
#  dia_tres_procura_stella,
dia_tres_procura_stella,
#  dia_tres_procura_real_bud,
vetor[44],
#  dia_tres_procura_real_stella
vetor[45],
# DIA 4
#  dia_quatro_sobras_bud,
vetor[46],
#  dia_quatro_sobras_stella,
vetor[47],
#  dia_quatro_v1,
vetor[48],
#  dia_quatro_v2,
vetor[49],
#  dia_quatro_v3,
vetor[50],
#  dia_quatro_quantidade_bud_v1,
vetor[51],
#  dia_quatro_quantidade_bud_v2,
vetor[52],
#  dia_quatro_quantidade_bud_v3,
vetor[53],
#  dia_quatro_quantidade_stella_v1,
vetor[54],
#  dia_quatro_quantidade_stella_v2,
vetor[55],
#  dia_quatro_quantidade_stella_v3,
vetor[56],
#  dia_quatro_sera_fds,
vetor[57],
#  dia_quatro_sera_normal,
vetor[58],
#  dia_quatro_procura_bud,
dia_quatro_procura_bud,
#  dia_quatro_procura_stella,
dia_quatro_procura_stella,
#  dia_quatro_procura_real_bud,
vetor[59],
#  dia_quatro_procura_real_stella
vetor[60],
# DIA 5
#  dia_cinco_sobras_bud,
vetor[61],
#  dia_cinco_sobras_stella,
vetor[62],
#  dia_cinco_v1,
vetor[63],
#  dia_cinco_v2,
vetor[64],
#  dia_cinco_v3,
vetor[65],
#  dia_cinco_quantidade_bud_v1,
vetor[66],
#  dia_cinco_quantidade_bud_v2,
vetor[67],
#  dia_cinco_quantidade_bud_v3,
vetor[68],
#  dia_cinco_quantidade_stella_v1,
vetor[69],
#  dia_cinco_quantidade_stella_v2,
vetor[70],
#  dia_cinco_quantidade_stella_v3,
vetor[71],
#  dia_cinco_sera_fds,
vetor[72],
#  dia_cinco_sera_normal,
vetor[73],
#  dia_cinco_procura_bud,
dia_cinco_procura_bud,
#  dia_cinco_procura_stella,
dia_cinco_procura_stella,
#  dia_cinco_procura_real_bud,
vetor[74],
#  dia_cinco_procura_real_stella
vetor[75],
# DIA 6
#  dia_seis_sobras_bud,
vetor[76],
#  dia_seis_sobras_stella,
vetor[77],
#  dia_seis_v1,
vetor[78],
#  dia_seis_v2,
vetor[79],
#  dia_seis_v3,
vetor[80],
#  dia_seis_quantidade_bud_v1,
vetor[81],
#  dia_seis_quantidade_bud_v2,
vetor[82],
#  dia_seis_quantidade_bud_v3,
vetor[83],
#  dia_seis_quantidade_stella_v1,
vetor[84],
#  dia_seis_quantidade_stella_v2,
vetor[85],
#  dia_seis_quantidade_stella_v3,
vetor[86],
#  dia_seis_sera_fds,
vetor[87],
#  dia_seis_sera_normal,
vetor[88],
#  dia_seis_procura_bud,
dia_seis_procura_bud,
#  dia_seis_procura_stella,
dia_seis_procura_stella,
#  dia_seis_procura_real_bud,
vetor[89],
#  dia_seis_procura_real_stella
vetor[90],
# DIA 7
#  dia_sete_sobras_bud,
vetor[91],
#  dia_sete_sobras_stella,
vetor[92],
#  dia_sete_v1,
vetor[93],
#  dia_sete_v2,
vetor[94],
#  dia_sete_v3,
vetor[95],
#  dia_sete_quantidade_bud_v1,
vetor[96],
#  dia_sete_quantidade_bud_v2,
vetor[97],
#  dia_sete_quantidade_bud_v3,
vetor[98],
#  dia_sete_quantidade_stella_v1,
vetor[99],
#  dia_sete_quantidade_stella_v2,
vetor[100],
#  dia_sete_quantidade_stella_v3,
vetor[101],
#  dia_sete_sera_fds,
vetor[102],
#  dia_sete_sera_normal,
vetor[103],
#  dia_sete_procura_bud,
dia_sete_procura_bud,
#  dia_sete_procura_stella,
dia_sete_procura_stella,
#  dia_sete_procura_real_bud,
vetor[104],
#  dia_sete_procura_real_stella
vetor[105]
);
return(lucro);
}
result <- mcsearch(eval,lower,upper,numero_iteracoes,type="max");
return(result);
}